# GET http://localhost:3000/

POST http://localhost:3001/CreateUser
Content-Type: application/json

{
    "nombreapellido": "Nahue Hernandez",
    "email": "nahue@gmail.com",
    "password": "123456"
}

###

GET http://localhost:3001/users

###

GET http://localhost:3001/user/2

###

PUT http://localhost:3001/user/5
Content-Type: application/json

{
    "nombreapellido": "Micaela Cuan",
    "email": "micucuan@gmail.com",
    "password": "123456"
}

###

DELETE http://localhost:3001/user/5

###

GET http://localhost:3001/lineas

###

GET http://localhost:3001/lineas/1

###

POST http://localhost:3001/colectivos/2
Content-Type: application/json

{
    "id_linea": 2,
    "interno": "2921"
}

###

POST http://localhost:3001/paradas/1
Content-Type: application/json

 {
      "latitud": "-34.616193",
      "longitud": "-58.382472",
      "id_linea": 1,
      "direccion": "Av. Congreso"
 }

 ###


GET http://localhost:3000/parada/3

###

GET http://localhost:3001/findLocation/-34.616193,-58.382472

###

GET http://localhost:3001/Findlinea/68

###

POST http://localhost:3001/CrearSolicitud
Content-Type: application/json

{
    "id_usuario": 8,
    "id_linea": 1,
    "paradaInicio": 1,
    "paradaDestino": 2
}

###

GET http://localhost:3001/solicitudes/2